[workspace]
members = [
    "edb/edgeql-parser",
    "edb/edgeql-parser/edgeql-parser-derive",
    "edb/edgeql-parser/edgeql-parser-python",
    "edb/graphql-rewrite",
    "edb/pgsql/edgedb_ext",
]
resolver = "2"

[profile.release]
debug = true
lto = true
